[package]
name = "timesheet-gen"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
chrono = "0.4"
regex = "1.5"
dirs = "4.0.0"
dialoguer = "0.8.0"